// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDknaWwUb9Q_qfkSU91IItPjvirvQSON_g',
    appId: '1:818896003379:web:a77c3ce51afc639684de46',
    messagingSenderId: '818896003379',
    projectId: 'firbaseauth-10d05',
    authDomain: 'firbaseauth-10d05.firebaseapp.com',
    storageBucket: 'firbaseauth-10d05.appspot.com',
    measurementId: 'G-5KRR370YKC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmZq472JjRNWILVly138DE5QOq3bVKaw0',
    appId: '1:818896003379:android:0c824e02481af07784de46',
    messagingSenderId: '818896003379',
    projectId: 'firbaseauth-10d05',
    storageBucket: 'firbaseauth-10d05.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXiWqo2RsDb4BYBUCFfDtbIAPA8VFukKg',
    appId: '1:818896003379:ios:a817550ef2f5d2fe84de46',
    messagingSenderId: '818896003379',
    projectId: 'firbaseauth-10d05',
    storageBucket: 'firbaseauth-10d05.appspot.com',
    iosBundleId: 'com.example.firebaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXiWqo2RsDb4BYBUCFfDtbIAPA8VFukKg',
    appId: '1:818896003379:ios:2fca52293354ee2984de46',
    messagingSenderId: '818896003379',
    projectId: 'firbaseauth-10d05',
    storageBucket: 'firbaseauth-10d05.appspot.com',
    iosBundleId: 'com.example.firebaseApp.RunnerTests',
  );
}
